//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookShelf
    {
        public System.Guid BookId { get; set; }
        public System.Guid ShelfId { get; set; }
        public int Counter { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Shelf Shelf { get; set; }
    }
}
